const express = require('express')
const cors = require('cors')
const db = require('./db')
const authRoutes = require('./routes/auth')
const dashboardRoutes = require('./routes/dashboard')
const kamarRoutes = require('./routes/kamar')
const penyewaRoutes = require('./routes/penyewa')
const pembayaranRoutes = require('./routes/pembayaran')
const pengeluaranRoutes = require('./routes/pengeluaran')
const laporanRoutes = require('./routes/laporan')
const pemesananRoutes = require('./routes/pemesanan')
const usersRoutes = require('./routes/users')
const userDashboardRoutes = require('./routes/userDashboard')
const PORT = process.env.PORT || 5000;
require('dotenv').config()

const app = express()
app.use(cors())
app.use(express.json())

app.use('/api/auth', authRoutes)
app.use('/api/dashboard', dashboardRoutes)
app.use('/api/kamar', kamarRoutes)
app.use('/api/penyewa', penyewaRoutes)
app.use('/api/pembayaran', pembayaranRoutes)
app.use('/api/pengeluaran', pengeluaranRoutes)
app.use('/api/pemesanan', pemesananRoutes)
app.use('/api/laporan', laporanRoutes)
app.use('/api/users', usersRoutes)
app.use('/api/user-dashboard', userDashboardRoutes)

app.listen(PORT, () => {
  console.log(`Server running di port ${PORT}`)
})

