export const cardStyle = "bg-white rounded-[2rem] shadow-sm border border-slate-100/80 hover:shadow-md transition-shadow duration-300"
export const inputStyle = "w-full px-5 py-3.5 bg-slate-50 border border-slate-100 rounded-2xl outline-none focus:bg-white focus:ring-4 focus:ring-indigo-50/50 focus:border-indigo-200 text-slate-800 placeholder-slate-400 transition-all"
export const labelStyle = "text-xs font-bold text-slate-500 uppercase ml-1 tracking-wider"
export const btnPrimary = "bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-2xl shadow-indigo-100 shadow-xl hover:-translate-y-0.5 transition-all"
export const btnAmber = "bg-amber-500 hover:bg-amber-600 text-white font-bold rounded-2xl shadow-amber-100 shadow-xl hover:-translate-y-0.5 transition-all"
export const thStyle = "p-5 text-xs font-black text-slate-400 uppercase tracking-widest cursor-pointer hover:text-indigo-600 transition-colors bg-slate-50/30"